name: Deploy Dist
on: [push,workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repositry
              uses: actions/checkout@v4

            - name: install node
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}    
            
            - name: install_dependencies
              run: npm install
              
            - name: run tests
              run: npm test 
              
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repositry
              uses: actions/checkout@v4

            - name: install node
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}    

            - name: install_dependencies
              run: npm install
            
            - name: build project
              run: npm run build
              
            - name: Deploy
              run: echo "Deploy Successfully!"


